name: Auto Merge Workflow
on:
  workflow_dispatch:
    inputs:
      branches:
        description: "Lista de ramas separadas por comas"
        required: true

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node for local action
        run: |
          cd ./.github/actions/auto-merge
          npm install
      - name: Run Auto Merge Action
        uses: ./.github/actions/auto-merge
        with:
          branches: ${{ github.event.inputs.branches }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
